language: ruby
cache: bundler
rvm:
  - 2.6.3
services:
  - postgresql
before_script:
  - psql -c 'create database near_mesa_test;' -U postgres
  - bundle install --jobs=3 --retry=3 --deployment
deploy:
  provider: heroku
  api_key:
    secure: flrD0FXep9Bc/LbalEnPJf8HFOkQlLI+KwOiSYFL2YTa86USOqitlLKwzFGe6BGRDkF9IBxigc5l+KZE3YYandJ2O8izKlpoADUQqB7BI5CZaeQjSrtBt7NYfZPW9e3vWcMbOE2lGVnQ82e2BLSR+g4MerfFktSYf/Rl4mTnd+j3Iyyscby/kuLtzVfBuYbN0SjlDTERhQZCpP9WVfqrWgraWOhxG4oJJBkK5Q7Lr3kOq5e0avhVvfXGV+rVDF2bIdu4fPcV2W1znpiWonyN4eZJj8mfvylfzUBDZq+OWQ10cYaYaCee3D31npfL9Mlb0souVhm0agm1GFMtDtsqYB2LlxDNW9j7EVJkkBCeYqEqIlJulltLXSXvyIDMHJIG+nL6Z8FUYuAFdkjxUwVNdZUhighOUJ8YuMj7odkLzAeNjBbdx9MsMlfQnOIGFY1q83b499ChYOSSuD9Xjcz4SEQFmWKYikLoexETjcHdgxI7LSuFKzd7pUyigLzcBaL78cd4hYffpMopdf8ZQqA9/242yBWR+Ultmxrgz5EKTP4USFe26V5Z+3sEMEiUhnaikbb7VqSvFf4p3Z1OfR1Koh8ayBwk+T0QzJ83tWk5DmAsfPiNiDEcXuL8VtFoLvVep/0owUVQG5j8vdg9GHytJYjWThWV3U+6pXzCw978dKk=
  app: near-mesa
  on:
    repo: jonaselan/near_mesa
notifications:
  email: false
